---
  - name: "configure zero client"
    hosts: localhost
    connection: local
    gather_facts: yes

    handlers:
    - name: reboot
      command: reboot

    tasks:
      
    # CONFIGURE AND UPDATE APT
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: true

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: true

    - name: Remove useless packages from the cache and purge
      apt:
        autoclean: yes
        force_apt_get: true

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
        purge: yes
        force_apt_get: true

    # Remove Openbox
    - name: Remove "openbox" package
      apt:
        name: openbox
        state: absent

     # INSTALL XORG AND Fluxbox
    - name: install xorg
      apt:
        name:
          - xserver-xorg
          - x11-xserver-utils
          - xinit
          - xorg
          - compton
        state: latest
        install_recommends: no
        
    # INSTALL FLUXBOX
    - name: install fluxbox
      apt:
        name:
          - fluxbox
        state: latest

    - name: create config directory for zero
      file:
        path: /home/zero/.config
        state: directory
        owner: zero
        group: zero

    - name: create config directory for fluxbox
      file:
        path: /home/zero/.fluxbox
        state: directory
        owner: zero
        group: zero

    - name: get fluxbox apps file
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/apps
        dest: /home/zero/.fluxbox/apps
        force: yes
        owner: zero
        group: zero
      notify: "reboot"
      
    - name: get fluxbox init file
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/init
        dest: /home/zero/.fluxbox/init
        force: yes
        owner: zero
        group: zero
      notify: "reboot"
              
    - name: get fluxbox keys file
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/keys
        dest: /home/zero/.fluxbox/keys
        force: yes
        owner: zero
        group: zero
      notify: "reboot"
      
    - name: get fluxbox menu file
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/menu
        dest: /home/zero/.fluxbox/menu
        force: yes
        owner: zero
        group: zero
      notify: "reboot"
    
    - name: get fluxbox startup file
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/startup
        dest: /home/zero/.fluxbox/startup
        force: yes
        owner: zero
        group: zero
      notify: "reboot"
      
    - name: get startup sound
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/ubuntu_startup.wav
        dest: /home/zero/.fluxbox/ubuntu_startup.wav
        force: yes
        owner: zero
        group: zero
      notify: "reboot"
      
    - name: get background picture
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/wp.jpg
        dest: /home/zero/.fluxbox/wp.jpg
        force: yes
        owner: zero
        group: zero
      notify: "reboot" 

    # INSTALL PULSEAUDIO
    - name: install PulseAudio
      apt:
        name:
          - pulseaudio
          - pavucontrol
          - alsa-base
          - alsa-utils
          - linux-sound-base
          - libasound2
        state: latest

      # INSTALL ZERO REQUIREMENTS
    - name: install other required packages for openbox config
      apt:
        name:
          - xterm
          - nodejs
        state: latest

    # INSTALL AND CONFIGURE CONKY
    - name: install conky
      apt:
        name: conky
        state: latest

    - name: get conky config
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/concyrc.lua
        dest: /home/zero/.config/conkyrc
        force: yes
        owner: zero
        group: zero
      notify: "reboot"

    # INSTALL AND CONFIGURE WORKSPACES
    - name: Add apt key for workspaces repo
      apt_key:
        url: https://workspaces-client-linux-public-key.s3-us-west-2.amazonaws.com/ADB332E7.asc
        state: present

    - name: Add workspaces repo
      apt_repository:
        repo: deb [arch=amd64] https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu bionic main
        filename: amazon-workspaces-clients
        update_cache: yes
        state: present

    - name: Install workspaces
      apt:
        name: workspacesclient
        state: latest

    #PARSEC Requirement
    - name: Install requirements for Parsec
      apt:
        name:
          - libqt5x11extras5
        state: latest
        
    - name: Ensure update-manager-core is installed.
      apt: name=update-manager-core state=present 
        
    - name: get .bash_profile
      get_url:
          url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/.bash_profile
          dest: /home/zero/.bash_profile
          force: yes
          owner: zero
          group: zero
      notify: "reboot"      

    - name: Run do-release-upgrade non-interactively.
      shell: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
      
    - name: Remove chromium
      shell: snap remove --purge chromium
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

    - name: get debian.list
      get_url:
          url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/debian.list
          dest: /etc/apt/sources.list.d/debian.list
          force: yes
          owner: zero
          group: zero
      notify: "reboot"
      
    - name: get chromium.pref
      get_url:
          url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/chromium.pref
          dest: /etc/apt/preferences.d/chromium.pref
          force: yes
          owner: zero
          group: zero
      notify: "reboot"           
                
    - name: remove chromium snap residuals
      command: apt remove chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra -y

    - name: add debian repo keys
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517

    - name: add debian repo keys
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138

    - name: add debian repo keys
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A

    - name: add debian repo keys
      shell: apt-key export 77E11517 | sudo gpg --batch --yes --dearmour -o /usr/share/keyrings/debian-buster.gpg

    - name: add debian repo keys
      shell: apt-key export 22F3D138 | sudo gpg --batch --yes --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg

    - name: add debian repo keys
      shell: apt-key export E562B32A | sudo gpg --batch --yes --dearmour -o /usr/share/keyrings/debian-security-buster.gpg

    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: true

    - name: Install Chromium for Parsec from Debian Repo
      apt:
        name: chromium 

    - name: Install additional packets missing after update to 20.04 (1)
      apt:
          name: xserver-xorg-video-fbdev
          state: latest

    - name: Install additional packets missing after update to 20.04 (2)
      apt:
          name: xserver-xorg-video-vesa
          state: latest

    - name: Install Parsec
      apt:
        deb: https://builds.parsecgaming.com/package/parsec-linux.deb
        state: latest
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04' 

    - name: get ubuntu-light.png
      get_url:
        url: https://raw.githubusercontent.com/aleks-ander/zero-client-update-to-fluxbox-20.04/master/fluxbox/wp.jpg
        dest: /usr/share/images/fluxbox/ubuntu-light.png
        force: yes
        owner: zero
        group: zero
      notify: "reboot" 

    # CONFIGURE IPTABLES TO MARK TRAFFIC AFTER INSTALL
    - stat:
        path: /root/install-complete
      register: install

    - name: mark traffic through ip tables
      iptables:
        chain: OUTPUT
        jump: DSCP
        table: mangle
        set_dscp_mark_class: CS5
        protocol: tcp
      when: install.stat.exists
      
    - name: Set Hostname
      hostname:
        name: zero-{{ ansible_default_ipv4.macaddress | hwaddr('bare') }}
